[package]
name = "functions"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "functions"
path = "src/functions.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
